### ISSUE TITLE
Problems introduced while round-tripping nm.json

### ISSUE THREAD

**Issue by kring** [TerriaJS/DataSourceEditor#1]
In item type `csv`:
`tableStyle.offset` was removed.  The value in the original was 0 so maybe it was deemed unnecessary?  It might actually be unnecessary, I'm not sure.

In item type `wms-getCapabilities`:
`legendUrl` was removed.  The value in the origin was an empty string, but that means "there is no legend".  Undefined means "use the default WMS legend URL".

Landgate `wms-getCapabilities` items had their `type` changed to `group`.

**Comment by kring** [comment]
The strategy of "don't include properties with their default value" might be suspect in general.  For example, the state init files need to explicitly specify `isOpen: false` for National Data Sets (even though that's the default) because they're intended to be overlaid on nm.json, which sets it to true.

In other words, for a property like `isOpen`, it may be necessary to have three states: true, false, and not specified.

**Comment by stevage** [comment]
> `tableStyle.offset` was  removed

Yeah, the behaviour is definitely that it doesn't save it if  the value is 0. Will need to investigate further to see if that's problematic, and/or hard to change.

> `legendUrl` was removed

As above, except clearly this is problematic.

> Landgate wms-getCapabilities items had their type changed to group

That behaviour means some part of the content didn't match the wms-getCapabalities schema. In this case, the schema was broken, and I've fixed it since then.

> The strategy of "don't include properties with their default value" might be suspect in general. 

Thanks - can you think of any other instances like this?

To explain how JSONEditor works:
- if a property exists in a JSON file, or it's `required` or in `defaultProperties` (or, configurably, always), then an editor is displayed for it
- if a user wants to set a value for a property that isn't in any of the above cases, they need to go to the "Properties" drop down and select it.
- if an editor is displayed, then a value gets saved, unless `remove_empty_properties` is set and the value is falsy (which it is) [I think]

So the options here are:
- remove properties from `defaultProperties` lists where the above behaviour is problematic (eg, `isOpen`)
- disable `remove_empty_properties` (this has the reverse negative behaviour of introducing fields where the user hasn't specified a value)
- more judiciously use `remove_empty_properties` at the level of individual objects rather than schema-wide
- attempt to change this behaviour somehow...

Probably the realistic way forward is:
- turn off `remove_empty_properties` schema-wide
- remove all non-required `defaultProperties`
- except in cases where:
  - it's safe to not save falsy values, in which case `remove_empty_properties` should be set true; or
  - it's safe to save default values even when not specified by the user, in which case `remove_empty_properties` should not be set.

**Comment by stevage** [comment]
(Oh I should mention that the above changes make the UX somewhat worse, as users will have to hunt through the Properties drop down, and probably won't realise that various settings are changeable.)
